CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100),
    salary DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

-- ATUALIZA TODOS OS USERS ADICIONANDO SALÁRIO ALEATÓRIO
UPDATE users SET salary = round(rand() * 10000);
